# WhiteSur Cursor Theme Role - Default Variables
---
# Main Toggle
vps_whitesur_cursor_install: true

# Source Repo
vps_whitesur_cursor_repo: "https://github.com/vinceliuice/WhiteSur-cursors.git"
vps_whitesur_cursor_version: "master"

# Theme to apply
vps_whitesur_cursor_theme: "WhiteSur-cursors"
