# WhiteSur Theme Role - Default Variables
---
# Main Toggle
vps_whitesur_install: true

# Options (corresponds to install.sh flags)
# --sharp: install sharp aurorae theme
vps_whitesur_sharp: false

# --opaque: install opaque theme version
vps_whitesur_opaque: false

# --round: install round theme version
vps_whitesur_round: false

# Kvantum (Required for best look)
vps_whitesur_install_kvantum: true

# Source Repo
vps_whitesur_repo: "https://github.com/vinceliuice/WhiteSur-kde.git"
vps_whitesur_version: "master"
