# Fonts Role - Metadata
---
dependencies:
  - common

galaxy_info:
  author: VPS RDP Workstation
  description: Developer fonts - JetBrains Mono Nerd Font, Powerline
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - trixie
