# Catppuccin Theme Role - Default Variables
---
vps_catppuccin_gtk_version: "1.0.3"
vps_catppuccin_cursors_version: "1.0.1"

# GTK Theme download URL
# Source: https://github.com/catppuccin/gtk/releases
vps_catppuccin_gtk_url: "https://github.com/catppuccin/gtk/releases/download/v{{ vps_catppuccin_gtk_version }}/catppuccin-mocha-blue-standard+default.zip"

# Cursors download URL
# Source: https://github.com/catppuccin/cursors/releases
vps_catppuccin_cursors_url: "https://github.com/catppuccin/cursors/releases/download/v{{ vps_catppuccin_cursors_version }}/catppuccin-mocha-blue-cursors.zip"

# Installation directories
vps_catppuccin_themes_dir: "/home/{{ vps_username }}/.themes"
vps_catppuccin_icons_dir: "/home/{{ vps_username }}/.icons"
