---
catppuccin_gtk_version: "1.0.3"
catppuccin_cursors_version: "1.0.1"

# GTK Theme download URL
# Source: https://github.com/catppuccin/gtk/releases
catppuccin_gtk_url: "https://github.com/catppuccin/gtk/releases/download/v{{ catppuccin_gtk_version }}/catppuccin-mocha-blue-standard+default.zip"

# Cursors download URL
# Source: https://github.com/catppuccin/cursors/releases
catppuccin_cursors_url: "https://github.com/catppuccin/cursors/releases/download/v{{ catppuccin_cursors_version }}/catppuccin-mocha-blue-cursors.zip"

# Installation directories
catppuccin_themes_dir: "/home/{{ vps_username }}/.themes"
catppuccin_icons_dir: "/home/{{ vps_username }}/.icons"
